services:
    app: 
        container_name: nuape
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        image: php84-fpm-sqlite
        restart: unless-stopped
        environment:
            PHP_OPCACHE_ENABLE: 1
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
            PHP_OPCACHE_MEMORY_CONSUMPTION: 256
            PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
            PHP_OPCACHE_JIT_BUFFER_SIZE: "100M"
            PHP_OPCACHE_JIT: "tracing"
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        networks:
            - api-network
    web-server:
        container_name: nginx
        image: nginx:1.24
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - ./:/var/www
        networks:
            - api-network
networks:
    api-network:
        driver: bridge
volumes:
    database_data: